import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Bot, Check, ChevronDown, CircleDot, Code2, Command, Database, GitBranch, Globe2, Layers3, LockKeyhole, Menu, MessageSquareText, MousePointer2, Plus, Search, Send, Sparkles, WandSparkles, X, Zap } from "lucide-react";

const navItems = ["Product", "Solutions", "Pricing", "Resources"];

const Logo = ({ compact = false }: { compact?: boolean }) => (
  <a href="#" className="group inline-flex items-center gap-2.5" aria-label="Orbital home">
    <span className="grid size-8 place-items-center rounded-[10px] border border-white/15 bg-white text-[#0B0B0C] shadow-[0_0_24px_rgba(255,255,255,.12)]"><CircleDot className="size-[18px] transition-transform duration-500 group-hover:rotate-180" strokeWidth={2.3} /></span>
    {!compact && <span className="text-[17px] font-semibold tracking-[-0.03em] text-white">orbital</span>}
  </a>
);

const ArrowButton = ({ children, href = "#pricing", secondary = false }: { children: React.ReactNode; href?: string; secondary?: boolean }) => (
  <a href={href} className={`group inline-flex min-h-12 items-center justify-center gap-2 rounded-[18px] px-5 text-sm font-semibold transition-all duration-300 active:scale-[.98] ${secondary ? "border border-white/12 bg-white/[.04] text-white hover:border-white/25 hover:bg-white/[.08]" : "bg-[#F9FAFB] text-[#0B0B0C] shadow-[0_8px_30px_rgba(255,255,255,.1)] hover:-translate-y-0.5 hover:bg-white hover:shadow-[0_12px_35px_rgba(255,255,255,.18)]"}`}>
    {children}<ArrowRight className="size-4 transition-transform duration-300 group-hover:translate-x-1" />
  </a>
);

const MiniBarChart = () => (
  <div className="flex h-24 items-end gap-1.5" aria-label="Revenue bar chart">
    {[31, 46, 39, 58, 51, 72, 64, 86, 74, 93, 82, 100].map((height, i) => <div key={i} className="group relative flex-1"><div className={`w-full origin-bottom rounded-t-[3px] bg-gradient-to-t ${i === 11 ? "from-cyan-500 to-cyan-300" : "from-white/10 to-white/25"} animate-grow-bar transition-colors group-hover:from-violet-500 group-hover:to-violet-300`} style={{ height: `${height * 0.8}px`, animationDelay: `${i * 70}ms` }} /></div>)}
  </div>
);

const Dashboard = () => (
  <div className="relative overflow-hidden rounded-t-[20px] border border-white/10 bg-[#111215] shadow-[0_40px_100px_rgba(0,0,0,.55)] sm:rounded-[24px]">
    <div className="flex h-12 items-center border-b border-white/[.07] px-4 sm:px-5"><div className="flex gap-1.5"><span className="size-2.5 rounded-full bg-white/15" /><span className="size-2.5 rounded-full bg-white/15" /><span className="size-2.5 rounded-full bg-white/15" /></div><div className="mx-auto hidden items-center gap-2 rounded-lg border border-white/[.06] bg-black/20 px-3 py-1 text-[10px] text-zinc-500 sm:flex"><LockKeyhole className="size-2.5" />app.orbital.so</div><Command className="size-4 text-zinc-600" /></div>
    <div className="grid min-h-[410px] grid-cols-[52px_1fr] sm:grid-cols-[180px_1fr] lg:min-h-[570px] lg:grid-cols-[210px_1fr]">
      <aside className="border-r border-white/[.07] p-2.5 sm:p-4"><div className="mb-6 flex items-center gap-2 px-1 sm:px-2"><span className="grid size-6 place-items-center rounded-md bg-violet-500 text-[10px] font-bold">N</span><span className="hidden text-xs font-medium text-zinc-300 sm:block">Northstar</span></div><div className="space-y-1 text-[11px] text-zinc-500">{[BarChart3, MousePointer2, Layers3, MessageSquareText].map((Icon, i) => <div key={i} className={`flex items-center gap-2 rounded-lg p-2 ${i === 0 ? "bg-white/[.07] text-zinc-200" : ""}`}><Icon className="size-3.5 shrink-0" /><span className="hidden sm:block">{["Overview", "Journeys", "Segments", "Feedback"][i]}</span></div>)}</div><div className="mt-8 hidden border-t border-white/[.06] pt-4 sm:block"><p className="px-2 text-[9px] uppercase tracking-[.18em] text-zinc-700">Workspace</p><p className="mt-3 px-2 text-[11px] text-zinc-500">Invite members</p><p className="mt-3 px-2 text-[11px] text-zinc-500">Data sources</p></div></aside>
      <div className="min-w-0 p-4 sm:p-6 lg:p-8">
        <div className="mb-6 flex items-start justify-between"><div><p className="text-[10px] text-zinc-600">Workspace / Overview</p><h3 className="mt-1.5 text-base font-semibold tracking-tight sm:text-xl">Good morning, Maya</h3></div><button className="hidden items-center gap-1.5 rounded-lg bg-white px-3 py-2 text-[10px] font-semibold text-black sm:flex"><Plus className="size-3" />New report</button></div>
        <div className="grid gap-3 sm:grid-cols-3">{[["Monthly revenue", "$482,690", "+24.8%"], ["Active users", "18,429", "+12.2%"], ["Conversion", "8.42%", "+3.1%"]].map((item, i) => <div key={item[0]} className="rounded-xl border border-white/[.07] bg-white/[.025] p-3.5 lg:p-4"><p className="text-[9px] text-zinc-500 lg:text-[10px]">{item[0]}</p><p className="mt-2 text-base font-semibold tracking-tight lg:text-xl">{item[1]}</p><p className={`mt-1 text-[9px] ${i === 0 ? "text-cyan-400" : "text-emerald-400"}`}>{item[2]} <span className="text-zinc-600">vs last month</span></p></div>)}</div>
        <div className="mt-3 grid gap-3 lg:grid-cols-[1.65fr_1fr]"><div className="rounded-xl border border-white/[.07] bg-white/[.025] p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-medium">Revenue performance</p><p className="mt-1 text-[9px] text-zinc-600">Jan 01 - Dec 31, 2025</p></div><span className="rounded-md border border-white/[.08] px-2 py-1 text-[9px] text-zinc-500">Monthly</span></div><MiniBarChart /><div className="mt-2 flex justify-between text-[8px] text-zinc-700"><span>JAN</span><span>MAR</span><span>MAY</span><span>JUL</span><span>SEP</span><span>NOV</span></div></div><div className="rounded-xl border border-violet-400/15 bg-gradient-to-b from-violet-500/[.08] to-transparent p-4"><div className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded-lg bg-violet-500/20"><Sparkles className="size-3 text-violet-300" /></span><p className="text-[11px] font-medium">Orbital AI</p><span className="ml-auto size-1.5 animate-pulse rounded-full bg-cyan-400" /></div><p className="mt-4 text-[11px] leading-5 text-zinc-400">Revenue accelerated after the new onboarding flow launched. Enterprise conversion is up <span className="text-white">18.4%</span>.</p><div className="mt-4 border-t border-white/[.07] pt-3"><p className="text-[9px] text-zinc-600">Suggested action</p><p className="mt-1.5 text-[10px] text-zinc-300">Expand the flow to team accounts</p></div></div></div>
        <div className="mt-3 hidden overflow-hidden rounded-xl border border-white/[.07] sm:block"><div className="grid grid-cols-[1.5fr_1fr_1fr_.7fr] border-b border-white/[.07] bg-white/[.025] px-4 py-2.5 text-[9px] text-zinc-600"><span>Top journeys</span><span>Users</span><span>Conversion</span><span>Trend</span></div>{[["Product signup", "6,820", "14.8%", "+22%"], ["Team invitation", "4,106", "11.2%", "+9%"]].map(row => <div key={row[0]} className="grid grid-cols-[1.5fr_1fr_1fr_.7fr] px-4 py-2.5 text-[10px] text-zinc-400 [&+&]:border-t [&+&]:border-white/[.05]"><span className="text-zinc-300">{row[0]}</span><span>{row[1]}</span><span>{row[2]}</span><span className="text-emerald-400">{row[3]}</span></div>)}</div>
      </div>
    </div>
  </div>
);

const SectionHeading = ({ eyebrow, title, copy, center = false }: { eyebrow: string; title: React.ReactNode; copy: string; center?: boolean }) => <div className={`reveal max-w-2xl ${center ? "mx-auto text-center" : ""}`}><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-cyan-400">{eyebrow}</p><h2 className="text-3xl font-semibold leading-[1.08] tracking-[-0.045em] text-white sm:text-5xl">{title}</h2><p className={`mt-5 max-w-xl text-base leading-7 text-zinc-400 ${center ? "mx-auto" : ""}`}>{copy}</p></div>;

const features = [
  { icon: BarChart3, title: "Signals, not noise", text: "Unify product, revenue, and customer data into one live operating view.", color: "text-cyan-300" },
  { icon: WandSparkles, title: "Answers in seconds", text: "Ask questions in plain language and get sourced, decision-ready analysis.", color: "text-violet-300" },
  { icon: Zap, title: "Built for momentum", text: "Automate recurring reports, alerts, and workflows without engineering queues.", color: "text-amber-300" },
];
const faqs = [
  ["How quickly can we get started?", "Most teams connect their first data source and build a live workspace in under 15 minutes. Our guided importer handles the mapping."],
  ["Does Orbital replace our data warehouse?", "No. Orbital works with your existing stack and adds a fast, intelligent operating layer on top of it."],
  ["How is our data protected?", "Orbital is SOC 2 Type II compliant, supports SSO and SCIM, and encrypts data in transit and at rest."],
  ["Can non-technical teams use it?", "Yes. Natural-language questions, templates, and guided workflows remove the need for SQL."],
];

export default function App() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [annual, setAnnual] = useState(true);
  const [openFaq, setOpenFaq] = useState(0);
  const [previewTab, setPreviewTab] = useState("Analyze");

  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => entry.isIntersecting && entry.target.classList.add("revealed")), { threshold: 0.12 }); document.querySelectorAll(".reveal").forEach(el => observer.observe(el)); return () => observer.disconnect(); }, []);

  return <div className="min-h-screen overflow-x-hidden bg-[#0B0B0C] text-[#F9FAFB] selection:bg-violet-500/40">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/[.07] bg-[#0B0B0C]/75 backdrop-blur-xl"><nav className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8" aria-label="Primary navigation"><Logo /><div className="hidden items-center gap-7 md:flex">{navItems.map(item => <a key={item} href={`#${item.toLowerCase()}`} className="text-sm text-zinc-400 transition-colors hover:text-white">{item}</a>)}</div><div className="hidden items-center gap-3 md:flex"><a href="#signin" className="px-3 text-sm text-zinc-400 hover:text-white">Sign in</a><a href="#pricing" className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-black transition-transform hover:-translate-y-0.5">Start free</a></div><button onClick={() => setMobileOpen(!mobileOpen)} className="grid size-10 place-items-center rounded-xl border border-white/10 md:hidden" aria-label="Toggle menu" aria-expanded={mobileOpen}>{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></nav>{mobileOpen && <div className="border-t border-white/10 bg-[#0B0B0C] p-4 md:hidden">{navItems.map(item => <a onClick={() => setMobileOpen(false)} key={item} href={`#${item.toLowerCase()}`} className="block border-b border-white/[.06] py-4 text-sm text-zinc-300">{item}</a>)}<a href="#pricing" className="mt-4 flex h-12 items-center justify-center rounded-xl bg-white text-sm font-semibold text-black">Start free</a></div>}</header>

    <main>
      <section className="relative min-h-screen overflow-hidden pt-16" aria-labelledby="hero-title"><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:64px_64px] [mask-image:linear-gradient(to_bottom,black,transparent_80%)]" /><div className="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[900px] -translate-x-1/2 rounded-full bg-violet-600/[.09] blur-[120px]" /><div className="relative mx-auto max-w-7xl px-4 pt-20 text-center sm:px-6 sm:pt-28 lg:px-8"><div className="animate-fade-up mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[.035] px-3 py-1.5 text-xs text-zinc-400"><span className="size-1.5 rounded-full bg-cyan-400 shadow-[0_0_12px_#22D3EE]" />Orbital 2.0 is now live <ArrowRight className="size-3" /></div><h1 id="hero-title" className="animate-fade-up-delay mx-auto max-w-5xl text-[clamp(3rem,8vw,7.25rem)] font-semibold leading-[.88] tracking-[-0.065em]">Turn every signal into <span className="bg-gradient-to-r from-white via-zinc-200 to-zinc-500 bg-clip-text text-transparent">momentum.</span></h1><p className="animate-fade-up-delay-2 mx-auto mt-7 max-w-2xl text-base leading-7 text-zinc-400 sm:text-lg">Orbital is the intelligent operating system that helps modern teams understand performance, decide faster, and grow with clarity.</p><div className="animate-fade-up-delay-2 mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ArrowButton>Start free</ArrowButton><ArrowButton href="#demo" secondary>Book demo</ArrowButton></div><p className="mt-4 text-[11px] text-zinc-600">No credit card required. Setup in minutes.</p><div className="relative mx-auto mt-16 max-w-6xl text-left sm:mt-24"><div className="absolute -inset-8 bg-gradient-to-t from-violet-500/10 via-cyan-400/[.05] to-transparent blur-3xl" /><div className="relative animate-dashboard-in"><Dashboard /></div></div></div><a href="#trusted" aria-label="Scroll to explore" className="absolute bottom-6 left-8 hidden items-center gap-3 text-[10px] uppercase tracking-[.2em] text-zinc-600 xl:flex"><span className="flex h-10 w-6 justify-center rounded-full border border-white/15 pt-2"><span className="h-1.5 w-1 animate-scroll rounded-full bg-white/60" /></span>Scroll to explore</a></section>

      <section id="trusted" className="border-y border-white/[.07] py-12 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-center text-[10px] font-medium uppercase tracking-[.22em] text-zinc-600">Trusted by ambitious teams at</p><div className="mt-8 grid grid-cols-2 gap-y-7 text-center text-base font-semibold tracking-tight text-zinc-500 sm:grid-cols-5"><span>Monogram</span><span className="font-serif italic">Rayon</span><span className="tracking-[.12em]">NORTHSTAR</span><span>unmake</span><span className="col-span-2 sm:col-span-1">MOSAIC+</span></div></div></section>

      <section id="product" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="One operating system" title={<>See what matters.<br />Move while it matters.</>} copy="Orbital turns fragmented information into a clear view of your business, so every team can act with confidence." /><div className="mt-16 grid gap-px overflow-hidden rounded-[20px] border border-white/[.08] bg-white/[.08] lg:grid-cols-3">{features.map(({ icon: Icon, title, text, color }, i) => <article key={title} className="group reveal bg-[#101114] p-7 transition-colors duration-500 hover:bg-[#15161A] sm:p-9" style={{ transitionDelay: `${i * 100}ms` }}><div className="mb-12 flex items-center justify-between"><Icon className={`size-6 ${color}`} strokeWidth={1.6} /><span className="font-mono text-[10px] text-zinc-700">0{i + 1}</span></div><h3 className="text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{text}</p><div className="mt-8 h-px w-8 bg-white/15 transition-all duration-500 group-hover:w-full group-hover:bg-gradient-to-r group-hover:from-violet-500 group-hover:to-transparent" /></article>)}</div></div></section>

      <section className="border-y border-white/[.07] bg-[#0E0F11] py-24 sm:py-32" aria-labelledby="showcase-title"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-violet-400">Product showcase</p><h2 id="showcase-title" className="max-w-2xl text-3xl font-semibold tracking-[-.045em] sm:text-5xl">Clarity from question to action.</h2></div><div className="flex w-fit rounded-xl border border-white/[.08] bg-black/25 p-1" role="tablist">{["Analyze", "Automate", "Collaborate"].map(tab => <button key={tab} onClick={() => setPreviewTab(tab)} role="tab" aria-selected={previewTab === tab} className={`rounded-lg px-3 py-2 text-xs transition-all sm:px-4 ${previewTab === tab ? "bg-white/10 text-white shadow-sm" : "text-zinc-600 hover:text-zinc-300"}`}>{tab}</button>)}</div></div>
        <div className="reveal relative mt-12 grid min-h-[560px] overflow-hidden rounded-[20px] border border-white/[.09] bg-[#111215] lg:grid-cols-[1fr_1.35fr]"><div className="flex flex-col justify-between border-b border-white/[.07] p-7 sm:p-10 lg:border-b-0 lg:border-r"><div><span className="grid size-11 place-items-center rounded-xl border border-violet-400/20 bg-violet-500/10 text-violet-300">{previewTab === "Analyze" ? <Search className="size-5" /> : previewTab === "Automate" ? <Zap className="size-5" /> : <MessageSquareText className="size-5" />}</span><h3 className="mt-8 text-2xl font-semibold tracking-tight">{previewTab === "Analyze" ? "Ask your business anything." : previewTab === "Automate" ? "Put insight on autopilot." : "Decide together, faster."}</h3><p className="mt-4 max-w-sm text-sm leading-6 text-zinc-500">{previewTab === "Analyze" ? "Orbital understands your metrics, customers, and context. Get a clear answer with every source attached." : previewTab === "Automate" ? "Build intelligent workflows that monitor changes, summarize results, and alert the right people." : "Turn live analysis into shared decisions without screenshots, exports, or stale slide decks."}</p></div><div className="mt-12 space-y-4">{["Grounded in your live data", "Transparent source references", "Enterprise-grade permissions"].map(item => <div key={item} className="flex items-center gap-3 text-xs text-zinc-400"><Check className="size-4 text-cyan-400" />{item}</div>)}</div></div>
        <div className="relative flex items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_50%_25%,rgba(124,58,237,.13),transparent_45%)] p-5 sm:p-10"><div className="w-full max-w-xl rounded-[18px] border border-white/10 bg-[#17181B] shadow-2xl"><div className="flex items-center gap-2 border-b border-white/[.07] p-4"><Bot className="size-4 text-violet-300" /><span className="text-xs font-medium">Ask Orbital</span><span className="ml-auto text-[9px] text-zinc-600">Across 12 sources</span></div><div className="space-y-5 p-5 sm:p-7"><div className="ml-auto max-w-[85%] rounded-2xl rounded-br-md bg-white/10 px-4 py-3 text-xs leading-5 text-zinc-200">What changed in enterprise conversion this quarter?</div><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-violet-500/20"><Sparkles className="size-3.5 text-violet-300" /></span><div><p className="text-xs leading-5 text-zinc-300">Enterprise conversion rose <strong className="text-white">18.4%</strong>, primarily driven by the new guided onboarding path.</p><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg border border-white/[.07] bg-black/20 p-3"><p className="text-[9px] text-zinc-600">Conversion</p><p className="mt-1 text-base font-semibold">12.8% <span className="text-[9px] text-emerald-400">+18.4%</span></p></div><div className="rounded-lg border border-white/[.07] bg-black/20 p-3"><p className="text-[9px] text-zinc-600">Time to value</p><p className="mt-1 text-base font-semibold">2.1 days</p></div></div><div className="mt-3 flex gap-2 text-[9px] text-zinc-600"><span className="rounded-md bg-white/[.05] px-2 py-1">Stripe / revenue</span><span className="rounded-md bg-white/[.05] px-2 py-1">HubSpot / pipeline</span></div></div></div></div><div className="m-4 flex items-center rounded-xl border border-white/10 bg-black/20 p-2 pl-4"><span className="text-xs text-zinc-600">Ask a follow-up...</span><button className="ml-auto grid size-8 place-items-center rounded-lg bg-white text-black" aria-label="Send question"><Send className="size-3.5" /></button></div></div></div></div>
      </div></section>

      <section id="solutions" className="py-24 sm:py-32"><div className="mx-auto grid max-w-7xl gap-16 px-4 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div className="reveal order-2 lg:order-1"><div className="rounded-[20px] border border-white/[.08] bg-[#111215] p-5 sm:p-8"><div className="flex items-center justify-between"><p className="text-xs font-medium">Growth forecast</p><span className="text-[9px] text-zinc-600">Confidence 94%</span></div><svg className="mt-8 w-full" viewBox="0 0 500 220" role="img" aria-label="Growth forecast line chart"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22D3EE" stopOpacity=".2"/><stop offset="1" stopColor="#22D3EE" stopOpacity="0"/></linearGradient></defs>{[40,85,130,175].map(y => <line key={y} x1="0" y1={y} x2="500" y2={y} stroke="white" strokeOpacity=".06" />)}<path d="M0 185 C55 181 76 160 120 164 S185 130 226 139 S298 96 340 104 S410 59 500 36 L500 220 L0 220Z" fill="url(#chartFill)"/><path className="animate-draw" d="M0 185 C55 181 76 160 120 164 S185 130 226 139 S298 96 340 104 S410 59 500 36" fill="none" stroke="#22D3EE" strokeWidth="2"/><path d="M340 104 C390 85 420 48 500 21" fill="none" stroke="#7C3AED" strokeWidth="2" strokeDasharray="5 6"/><circle cx="340" cy="104" r="5" fill="#0B0B0C" stroke="#22D3EE" strokeWidth="2"/></svg><div className="mt-2 flex justify-between text-[9px] text-zinc-700"><span>Q1</span><span>Q2</span><span>Q3</span><span>Q4</span></div></div></div><div className="order-1 lg:order-2"><SectionHeading eyebrow="Built to compound" title="A faster rhythm for the whole company." copy="Replace manual reporting and scattered tools with one shared layer that gets smarter as your team grows." /><div className="mt-10 grid gap-7 sm:grid-cols-2">{[["8.6x", "faster reporting"], ["23%", "higher activation"], ["14 hrs", "saved per team, weekly"], ["99.99%", "platform uptime"]].map(([n, l]) => <div key={l} className="border-l border-white/10 pl-5"><p className="text-2xl font-semibold tracking-tight text-white">{n}</p><p className="mt-1 text-xs text-zinc-600">{l}</p></div>)}</div></div></div></section>

      <section className="border-y border-white/[.07] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading center eyebrow="Integrations" title="Works with your stack. Not against it." copy="Connect the tools you already trust. Orbital keeps every signal synchronized and ready to use." /><div className="reveal mx-auto mt-16 grid max-w-4xl grid-cols-3 gap-px overflow-hidden rounded-[20px] border border-white/[.08] bg-white/[.08] sm:grid-cols-6">{[{i:Database,n:"Snowflake"},{i:GitBranch,n:"GitHub"},{i:Globe2,n:"HubSpot"},{i:Code2,n:"Segment"},{i:Layers3,n:"Stripe"},{i:Command,n:"Linear"}].map(({i:Icon,n}) => <div key={n} className="group grid aspect-square place-items-center bg-[#0E0F11] transition-colors hover:bg-[#17181B]"><div className="text-center"><Icon className="mx-auto size-6 text-zinc-500 transition-all group-hover:-translate-y-1 group-hover:text-white" strokeWidth={1.5}/><p className="mt-3 text-[10px] text-zinc-600 group-hover:text-zinc-400">{n}</p></div></div>)}</div><p className="mt-8 text-center text-xs text-zinc-600">Plus 80+ native integrations and a flexible API.</p></div></section>

      <section className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Customer story" title="The best teams run on clarity." copy="From first signal to final decision, Orbital gives operators the confidence to move." /><figure className="reveal mt-16 grid border-y border-white/[.09] py-10 lg:grid-cols-[.8fr_2fr] lg:gap-20 lg:py-16"><div><p className="text-2xl font-semibold tracking-tight">NORTHSTAR</p><p className="mt-2 text-xs text-zinc-600">Infrastructure / 420 employees</p></div><div><blockquote className="mt-10 max-w-3xl text-2xl font-medium leading-[1.4] tracking-[-.03em] text-zinc-200 sm:text-4xl lg:mt-0">“Orbital changed how we operate. We went from debating whose spreadsheet was right to making the decision in the room.”</blockquote><figcaption className="mt-8 flex items-center gap-4"><div className="grid size-11 place-items-center rounded-full bg-gradient-to-br from-zinc-600 to-zinc-800 text-sm font-semibold">AM</div><div><p className="text-sm font-medium">Avery Morgan</p><p className="mt-0.5 text-xs text-zinc-600">VP of Operations, Northstar</p></div></figcaption></div></figure></div></section>

      <section id="pricing" className="border-y border-white/[.07] bg-[#0E0F11] py-24 sm:py-32"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><SectionHeading eyebrow="Pricing" title="Start small. Scale without limits." copy="One simple plan with everything your team needs to move faster." /><button onClick={() => setAnnual(!annual)} className="flex w-fit items-center gap-3 rounded-full border border-white/10 bg-black/20 p-1 pl-4 text-xs text-zinc-400" aria-label="Toggle annual billing"><span>Annual <span className="text-cyan-400">-20%</span></span><span className="relative h-7 w-12 rounded-full bg-white/10"><span className={`absolute top-1 size-5 rounded-full bg-white transition-all ${annual ? "left-6" : "left-1"}`} /></span></button></div><div className="mt-16 grid overflow-hidden rounded-[20px] border border-white/[.09] lg:grid-cols-[1.35fr_.65fr]"><div className="p-7 sm:p-10 lg:border-r lg:border-white/[.09]"><p className="text-sm font-semibold">Orbital Pro</p><div className="mt-6 flex items-end gap-2"><span className="text-5xl font-semibold tracking-[-.05em]">${annual ? "39" : "49"}</span><span className="pb-1 text-sm text-zinc-600">per user / month</span></div><p className="mt-5 max-w-md text-sm leading-6 text-zinc-500">Everything you need to connect your data, understand performance, and automate your operating rhythm.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{["Unlimited dashboards", "Orbital AI analyst", "All integrations", "Automated reports", "Custom metrics", "Priority support"].map(item => <div key={item} className="flex gap-2.5 text-xs text-zinc-400"><Check className="size-4 text-cyan-400" />{item}</div>)}</div></div><div className="flex flex-col justify-center bg-white/[.02] p-7 sm:p-10"><p className="text-xs font-medium text-zinc-500">Free for 14 days</p><a href="#signup" className="group mt-5 flex h-13 items-center justify-center gap-2 rounded-[18px] bg-white font-semibold text-black transition-all hover:-translate-y-0.5 hover:shadow-[0_12px_30px_rgba(255,255,255,.12)]">Start free <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></a><a href="#demo" className="mt-3 flex h-13 items-center justify-center rounded-[18px] border border-white/10 text-sm font-semibold text-white transition-colors hover:bg-white/[.05]">Talk to sales</a><p className="mt-5 text-center text-[10px] text-zinc-700">Cancel anytime. No setup fees.</p></div></div></div></section>

      <section id="resources" className="py-24 sm:py-32"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><SectionHeading center eyebrow="FAQ" title="Questions, answered." copy="Everything you need to know before bringing Orbital to your team." /><div className="mt-14 divide-y divide-white/[.08] border-y border-white/[.08]">{faqs.map(([q,a], i) => <div key={q}><button onClick={() => setOpenFaq(openFaq === i ? -1 : i)} className="flex w-full items-center justify-between gap-8 py-6 text-left text-sm font-medium sm:text-base" aria-expanded={openFaq === i}>{q}<ChevronDown className={`size-4 shrink-0 text-zinc-500 transition-transform ${openFaq === i ? "rotate-180" : ""}`} /></button><div className={`grid transition-all duration-300 ${openFaq === i ? "grid-rows-[1fr] pb-6" : "grid-rows-[0fr]"}`}><p className="max-w-2xl overflow-hidden text-sm leading-6 text-zinc-500">{a}</p></div></div>)}</div></div></section>

      <section className="px-4 pb-24 sm:px-6 sm:pb-32 lg:px-8"><div className="relative mx-auto max-w-7xl overflow-hidden rounded-[24px] border border-white/[.09] bg-[#15161A] px-6 py-20 text-center sm:px-12 sm:py-28"><div className="pointer-events-none absolute inset-x-0 -top-48 mx-auto h-96 w-[700px] rounded-full bg-violet-600/20 blur-[110px]"/><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:48px_48px]"/><div className="relative"><Logo compact/><h2 className="mx-auto mt-7 max-w-3xl text-4xl font-semibold leading-[1] tracking-[-.055em] sm:text-6xl">Your next decision should take seconds.</h2><p className="mx-auto mt-6 max-w-xl text-sm leading-6 text-zinc-400">Join the teams building a faster, clearer operating rhythm with Orbital.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><ArrowButton>Start free</ArrowButton><ArrowButton href="#demo" secondary>Book demo</ArrowButton></div></div></div></section>
    </main>

    <footer className="border-t border-white/[.07] py-12"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Logo/><p className="mt-5 max-w-xs text-xs leading-5 text-zinc-600">The intelligent operating system for teams that move with clarity.</p></div>{[["Product","Overview","Orbital AI","Integrations","Pricing"],["Company","About","Customers","Careers","Contact"],["Resources","Changelog","Documentation","Security","Status"]].map(col => <div key={col[0]}><p className="text-xs font-medium text-zinc-300">{col[0]}</p>{col.slice(1).map(x => <a key={x} href="#" className="mt-3 block text-xs text-zinc-600 transition-colors hover:text-white">{x}</a>)}</div>)}</div><div className="mt-12 flex flex-col gap-5 border-t border-white/[.07] pt-6 text-[10px] text-zinc-700 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Orbital Labs, Inc.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#">LinkedIn</a><a href="#">X / Twitter</a></div></div></div></footer>
  </div>;
}