import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { Activity, ArrowDown, ArrowRight, Award, Baby, Brain, CalendarDays, Check, ChevronDown, Clock3, HeartPulse, Hospital, MapPin, Menu, Phone, Search, ShieldCheck, Sparkles, X, Zap, Quote, Star, Instagram, Linkedin, Facebook } from 'lucide-react'

const specialties = [
  { icon: HeartPulse, name: 'Cardiology', text: 'Comprehensive heart care, diagnostics, and prevention.', doctors: '4 specialists available' },
  { icon: Brain, name: 'Neurology', text: 'Expert evaluation and care for brain and nervous system health.', doctors: '3 specialists available' },
  { icon: Baby, name: 'Pediatrics', text: 'Gentle, family-centered care from infancy through adolescence.', doctors: '5 specialists available' },
  { icon: Activity, name: 'Internal Medicine', text: 'Personalized primary care for your long-term wellbeing.', doctors: '8 specialists available' },
  { icon: Sparkles, name: 'Dermatology', text: 'Evidence-based medical and cosmetic skin treatments.', doctors: '3 specialists available' },
  { icon: Zap, name: 'Diagnostics', text: 'Precise imaging and lab testing with rapid, clear results.', doctors: 'Same-day appointments' },
]
const doctors = [
  { name: 'Dr. Amara Okafor', role: 'Consultant, Internal Medicine', exp: '12 years experience', image: '/images/doctor-amara.jpg' },
  { name: 'Dr. James Bennett', role: 'Senior Cardiologist', exp: '15 years experience', image: '/images/doctor-james.jpg' },
  { name: 'Dr. Sofia Martinez', role: 'Consultant, Family Medicine', exp: '10 years experience', image: '/images/doctor-team.jpg' },
]
const faqs = [
  ['How quickly can I see a doctor?', 'We reserve daily appointment slots for urgent and same-day care. Most patients can be seen within 24 hours, either in person or by secure video visit.'],
  ['Do you accept my insurance?', 'We work with most major insurance providers. Our patient care team will verify your benefits before your visit so there are no surprises.'],
  ['What should I bring to my appointment?', 'Please bring a photo ID, insurance card, current medication list, and any relevant medical records or test results.'],
  ['Can I manage my care online?', 'Yes. Our secure patient portal lets you view results, message your care team, request refills, and manage appointments.'],
]
const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' }, transition: { duration: .55 } }

function Logo({ light = false }: { light?: boolean }) {
  return <a href="#top" className="flex items-center gap-3" aria-label="Clarity Health home"><span className="grid size-10 place-items-center rounded-xl bg-[#0F766E] text-white shadow-sm"><HeartPulse size={22}/></span><span className={`text-xl font-bold tracking-[-.03em] ${light ? 'text-white' : 'text-[#163A5F]'}`}>Clarity<span className="font-medium text-[#0F766E]">Health</span></span></a>
}

export default function ClinicApp() {
  const [scrolled, setScrolled] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)
  const [faqOpen, setFaqOpen] = useState(0)
  const [submitted, setSubmitted] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 48); onScroll(); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const submit = (e: React.FormEvent) => { e.preventDefault(); setSubmitted(true); setTimeout(() => setSubmitted(false), 5000) }

  return <div id="top" className="min-h-screen bg-white text-[#263647] selection:bg-[#DFF6F0]">
    <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-300 ${scrolled ? 'border-b border-slate-200/80 bg-white/95 shadow-[0_4px_24px_rgba(22,58,95,.06)] backdrop-blur-xl' : 'bg-white/80 lg:bg-transparent'}`}>
      <nav className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 sm:px-8 lg:px-12" aria-label="Primary navigation">
        <Logo />
        <div className="hidden items-center gap-7 lg:flex">{['Specialties','Doctors','About','Resources'].map(item => <a key={item} href={`#${item.toLowerCase()}`} className="text-sm font-semibold text-[#33475B] transition hover:text-[#0F766E]">{item}</a>)}<a href="#contact" className="text-sm font-semibold text-[#33475B] hover:text-[#0F766E]">Contact</a></div>
        <div className="hidden items-center gap-3 lg:flex"><a href="tel:+15550199000" className="flex items-center gap-2 rounded-2xl px-3 py-3 text-sm font-semibold text-[#163A5F] hover:bg-white/70"><Phone size={17}/> (555) 019-9000</a><a href="#appointment" className="rounded-2xl bg-[#163A5F] px-5 py-3.5 text-sm font-bold text-white shadow-[0_8px_22px_rgba(22,58,95,.18)] transition hover:-translate-y-0.5 hover:bg-[#0F766E]">Book appointment</a></div>
        <button onClick={() => setMenuOpen(!menuOpen)} className="grid size-11 place-items-center rounded-xl bg-white text-[#163A5F] shadow-sm lg:hidden" aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button>
      </nav>
      {menuOpen && <div className="border-t border-slate-100 bg-white px-5 py-6 shadow-xl lg:hidden">{['Specialties','Doctors','About','Resources','Contact'].map(item => <a onClick={()=>setMenuOpen(false)} key={item} href={`#${item.toLowerCase()}`} className="block border-b border-slate-100 py-4 font-semibold text-[#163A5F]">{item}</a>)}<a onClick={()=>setMenuOpen(false)} href="#appointment" className="mt-5 block rounded-2xl bg-[#163A5F] px-5 py-4 text-center font-bold text-white">Book appointment</a></div>}
    </header>

    <main>
      <section className="relative min-h-[760px] overflow-hidden bg-[#F5F7FA] lg:min-h-screen" aria-labelledby="hero-heading">
        <div className="absolute inset-y-0 right-0 hidden w-[53%] overflow-hidden lg:block"><img src="/images/hero-doctor.jpg" alt="Doctor speaking warmly with a patient" className="h-full w-full object-cover object-center" fetchPriority="high"/><div className="absolute inset-0 bg-gradient-to-r from-[#F5F7FA] via-transparent to-transparent"/></div>
        <div className="mx-auto flex min-h-[760px] max-w-[1440px] items-center px-5 pb-16 pt-32 sm:px-8 lg:min-h-screen lg:px-12"><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="relative z-10 max-w-2xl lg:w-[51%]">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#0F766E]/15 bg-[#DFF6F0] px-4 py-2 text-xs font-bold uppercase tracking-[.13em] text-[#0F766E]"><ShieldCheck size={16}/> Trusted care, centered on you</div>
          <h1 id="hero-heading" className="text-[clamp(3rem,6vw,5.75rem)] font-bold leading-[.98] tracking-[-.055em] text-[#163A5F]">Healthcare that sees the <span className="text-[#0F766E]">whole you.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-[#4B5563] sm:text-xl">Exceptional doctors, thoughtful care, and modern medicine—all working together to help you live your healthiest life.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#appointment" className="group inline-flex items-center justify-center gap-3 rounded-2xl bg-[#163A5F] px-7 py-4 font-bold text-white shadow-[0_12px_28px_rgba(22,58,95,.2)] transition hover:-translate-y-0.5 hover:bg-[#0F766E]">Book appointment <ArrowRight size={19} className="transition group-hover:translate-x-1"/></a><a href="#doctors" className="inline-flex items-center justify-center gap-3 rounded-2xl border border-[#163A5F]/15 bg-white px-7 py-4 font-bold text-[#163A5F] shadow-sm transition hover:text-[#0F766E]"><Search size={19}/> Find a doctor</a></div>
          <div className="mt-10 grid gap-3 sm:grid-cols-3 lg:max-w-xl">{[['Licensed Doctors',Award],['Same-Day Visits',CalendarDays],['Modern Facilities',Hospital]].map(([text, Icon]) => <div key={text as string} className="flex items-center gap-2.5 text-sm font-semibold text-[#33475B]"><span className="grid size-8 place-items-center rounded-full bg-white text-[#0F766E] shadow-sm"><Icon size={16}/></span>{text as string}</div>)}</div>
        </motion.div></div><div className="absolute bottom-7 left-1/2 hidden -translate-x-1/2 items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#607080] lg:flex"><ArrowDown size={16} className="animate-bounce"/> Explore your care</div>
      </section>

      <section id="appointment" className="relative z-10 mx-auto -mt-8 max-w-[1344px] px-5 sm:px-8 lg:-mt-16"><motion.div {...reveal} className="overflow-hidden rounded-[20px] border border-white/80 bg-white shadow-[0_24px_60px_rgba(22,58,95,.13)]"><div className="grid lg:grid-cols-[.36fr_.64fr]">
        <div className="bg-[#163A5F] p-7 text-white sm:p-10"><span className="mb-5 grid size-12 place-items-center rounded-2xl bg-white/10"><CalendarDays/></span><h2 className="text-3xl font-bold tracking-tight">Ready to feel your best?</h2><p className="mt-3 leading-7 text-blue-100">Tell us what you need. Our care team will confirm your visit shortly.</p><div className="mt-7 flex items-center gap-3 border-t border-white/15 pt-6 text-sm text-blue-50"><Clock3 size={18}/> Average response time: 10 minutes</div></div>
        <form onSubmit={submit} className="grid gap-4 p-7 sm:grid-cols-2 sm:p-10" aria-label="Appointment request form"><label className="text-sm font-semibold text-[#33475B]">Your name<input required type="text" placeholder="Full name" className="mt-2 w-full rounded-2xl border border-slate-200 bg-[#F8FAFC] px-4 py-3.5 outline-none focus:border-[#0F766E] focus:ring-4 focus:ring-[#DFF6F0]"/></label><label className="text-sm font-semibold text-[#33475B]">Phone number<input required type="tel" placeholder="(555) 000-0000" className="mt-2 w-full rounded-2xl border border-slate-200 bg-[#F8FAFC] px-4 py-3.5 outline-none focus:border-[#0F766E] focus:ring-4 focus:ring-[#DFF6F0]"/></label><label className="text-sm font-semibold text-[#33475B]">Specialty<select className="mt-2 w-full rounded-2xl border border-slate-200 bg-[#F8FAFC] px-4 py-3.5 outline-none focus:border-[#0F766E]"><option>General consultation</option><option>Cardiology</option><option>Pediatrics</option><option>Neurology</option><option>Dermatology</option></select></label><label className="text-sm font-semibold text-[#33475B]">Preferred date<input required type="date" className="mt-2 w-full rounded-2xl border border-slate-200 bg-[#F8FAFC] px-4 py-3.5 outline-none focus:border-[#0F766E]"/></label><button className="rounded-2xl bg-[#0F766E] px-6 py-4 font-bold text-white shadow-[0_8px_20px_rgba(15,118,110,.18)] transition hover:-translate-y-0.5 hover:bg-[#0b615a] sm:col-span-2">Request appointment <ArrowRight className="ml-2 inline" size={18}/></button></form>
      </div></motion.div></section>

      <section id="about" className="px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto grid max-w-[1344px] gap-14 lg:grid-cols-2 lg:items-center">
        <motion.div {...reveal} className="relative"><div className="overflow-hidden rounded-[20px]"><img loading="lazy" src="/images/clinic-room.jpg" alt="Bright modern examination room" className="aspect-[4/3] w-full object-cover transition duration-700 hover:scale-[1.02]"/></div><div className="absolute -bottom-7 right-4 max-w-[260px] rounded-[18px] border border-white bg-white p-5 shadow-[0_18px_45px_rgba(22,58,95,.14)] sm:right-8"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-[#DFF6F0] text-[#0F766E]"><Award/></span><strong className="text-3xl text-[#163A5F]">25+</strong></div><p className="mt-2 text-sm leading-6 text-slate-600">Years setting a higher standard for patient care.</p></div></motion.div>
        <motion.div {...reveal}><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Welcome to Clarity Health</p><h2 className="mt-4 text-4xl font-bold leading-tight tracking-[-.04em] text-[#163A5F] sm:text-5xl">Medicine with more time, more listening, and more care.</h2><p className="mt-6 text-lg leading-8 text-slate-600">We bring primary and specialty care together in one calm, connected experience. Your physician knows your story, your care plan is always clear, and every detail is designed around your comfort.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[['One connected care team','Your providers collaborate around your complete health.'],['Answers you can understand','Clear guidance, transparent costs, and no rushed visits.']].map(x => <div key={x[0]}><div className="mb-3 flex items-center gap-2 font-bold text-[#163A5F]"><Check className="rounded-full bg-[#DFF6F0] p-1 text-[#0F766E]" size={24}/>{x[0]}</div><p className="text-sm leading-6 text-slate-600">{x[1]}</p></div>)}</div><a href="#doctors" className="mt-8 inline-flex items-center gap-2 font-bold text-[#0F766E] hover:gap-3">Meet our care team <ArrowRight size={18}/></a></motion.div>
      </div></section>

      <section id="specialties" className="bg-[#F5F7FA] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-[1344px]"><motion.div {...reveal} className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Care for every chapter</p><h2 className="mt-4 max-w-2xl text-4xl font-bold tracking-[-.04em] text-[#163A5F] sm:text-5xl">Expertise that works together.</h2></div><p className="max-w-md leading-7 text-slate-600">From everyday wellness to complex conditions, find coordinated expertise under one roof.</p></motion.div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{specialties.map((s,i) => <motion.article {...reveal} transition={{duration:.45,delay:i*.06}} key={s.name} className="group rounded-[20px] border border-slate-200 bg-white p-7 shadow-[0_5px_18px_rgba(22,58,95,.04)] transition duration-300 hover:-translate-y-1 hover:border-[#0F766E]/30 hover:shadow-[0_18px_40px_rgba(22,58,95,.1)]"><div className="flex items-start justify-between"><span className="grid size-13 place-items-center rounded-2xl bg-[#DCEFFD] text-[#163A5F] transition group-hover:bg-[#DFF6F0] group-hover:text-[#0F766E]"><s.icon size={25}/></span><ArrowRight className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-[#0F766E]"/></div><h3 className="mt-7 text-xl font-bold text-[#163A5F]">{s.name}</h3><p className="mt-3 min-h-12 leading-6 text-slate-600">{s.text}</p><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-5"><span className="text-xs font-bold text-[#0F766E]">{s.doctors}</span><a href="#appointment" className="text-sm font-bold text-[#163A5F] hover:text-[#0F766E]">Book now</a></div></motion.article>)}</div></div></section>

      <section id="doctors" className="px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-[1344px]"><motion.div {...reveal} className="text-center"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">People who care deeply</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] text-[#163A5F] sm:text-5xl">Doctors you can trust.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">Experienced specialists chosen as much for how they listen as for what they know.</p></motion.div><div className="mt-12 grid gap-6 md:grid-cols-3">{doctors.map((d,i) => <motion.article {...reveal} transition={{duration:.5,delay:i*.09}} key={d.name} className="group overflow-hidden rounded-[20px] border border-slate-200 bg-white"><div className="overflow-hidden bg-[#DCEFFD]"><img loading="lazy" src={d.image} alt={d.name} className={`aspect-[4/4.4] w-full object-cover transition duration-700 group-hover:scale-[1.02] ${i===2?'object-[55%_25%]':''}`}/></div><div className="p-6"><div className="mb-3 flex items-center gap-1 text-amber-500"><Star size={14} fill="currentColor"/><span className="ml-1 text-xs font-bold text-slate-500">4.9 patient rating</span></div><h3 className="text-xl font-bold text-[#163A5F]">{d.name}</h3><p className="mt-1 font-medium text-[#0F766E]">{d.role}</p><p className="mt-2 text-sm text-slate-500">{d.exp}</p><a href="#appointment" className="mt-5 flex items-center justify-between border-t border-slate-100 pt-5 text-sm font-bold text-[#163A5F] hover:text-[#0F766E]">View profile & availability <ArrowRight size={17}/></a></div></motion.article>)}</div></div></section>

      <section className="bg-[#163A5F] px-5 py-24 text-white sm:px-8"><div className="mx-auto grid max-w-[1344px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><motion.div {...reveal}><Quote className="text-[#62c7b9]" size={42}/><blockquote className="mt-6 text-3xl font-semibold leading-[1.35] tracking-[-.025em] sm:text-4xl">“For the first time in years, I felt truly listened to. Every person I met was kind, thorough, and completely focused on getting me well.”</blockquote><div className="mt-8"><p className="font-bold">Elena R.</p><p className="mt-1 text-sm text-blue-200">Primary care patient · 3 years</p></div><div className="mt-8 flex gap-2">{[1,2,3].map((n,i)=><button key={n} aria-label={`View testimonial ${n}`} className={`h-1.5 rounded-full ${i===0?'w-8 bg-[#62c7b9]':'w-4 bg-white/30'}`}/>)}</div></motion.div><motion.div {...reveal} className="overflow-hidden rounded-[20px]"><img loading="lazy" src="/images/compassion-care.jpg" alt="Doctor and patient shaking hands after a consultation" className="aspect-[4/3] w-full object-cover transition duration-700 hover:scale-[1.02]"/></motion.div></div></section>

      <section className="border-b border-slate-200 px-5 py-16 sm:px-8"><div className="mx-auto max-w-[1344px] text-center"><p className="text-sm font-bold uppercase tracking-[.15em] text-slate-500">Accepted by leading insurance plans</p><div className="mt-9 flex flex-wrap items-center justify-center gap-x-12 gap-y-7 text-xl font-bold text-[#607080] sm:gap-x-16"><span>BlueCross</span><span className="font-serif italic">Aetna</span><span>United<span className="text-[#0F766E]">Healthcare</span></span><span>CIGNA</span><span className="tracking-tight">HUMANA</span></div><a href="#contact" className="mt-8 inline-block text-sm font-bold text-[#0F766E] underline-offset-4 hover:underline">Check your coverage</a></div></section>

      <section id="resources" className="bg-[#F5F7FA] px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto grid max-w-[1344px] gap-14 lg:grid-cols-2"><motion.div {...reveal}><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Helpful answers</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] text-[#163A5F] sm:text-5xl">Before your visit.</h2><p className="mt-5 max-w-md leading-7 text-slate-600">Have another question? Our patient coordinators are here to help.</p><a href="tel:+15550199000" className="mt-7 inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 font-bold text-[#163A5F]"><Phone size={18}/> Call patient services</a></motion.div><div className="space-y-3">{faqs.map((f,i)=><motion.div {...reveal} key={f[0]} className="rounded-[18px] border border-slate-200 bg-white"><button onClick={()=>setFaqOpen(faqOpen===i?-1:i)} className="flex w-full items-center justify-between gap-4 p-5 text-left font-bold text-[#163A5F] sm:p-6" aria-expanded={faqOpen===i}>{f[0]}<ChevronDown className={`shrink-0 transition ${faqOpen===i?'rotate-180 text-[#0F766E]':''}`}/></button>{faqOpen===i&&<p className="px-5 pb-6 leading-7 text-slate-600 sm:px-6">{f[1]}</p>}</motion.div>)}</div></div></section>

      <section className="px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-[1344px]"><div className="flex items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Health, made clearer</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] text-[#163A5F]">From our physicians.</h2></div><a href="#resources" className="hidden items-center gap-2 font-bold text-[#0F766E] sm:flex">All articles <ArrowRight size={18}/></a></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[['PREVENTIVE CARE','7 health screenings that matter at every age','6 min read'],['HEART HEALTH','Small daily habits for a healthier heart','5 min read'],['FAMILY HEALTH','How to prepare for a better doctor visit','4 min read']].map((a,i)=><article key={a[1]} className="group rounded-[20px] border border-slate-200 p-7 transition hover:-translate-y-1 hover:shadow-[0_14px_32px_rgba(22,58,95,.08)]"><div className={`mb-8 grid aspect-[2/1] place-items-center rounded-2xl ${i===0?'bg-[#DFF6F0]':i===1?'bg-[#DCEFFD]':'bg-[#F4EBDD]'}`}><span className="grid size-16 place-items-center rounded-full bg-white text-[#163A5F] shadow-sm">{i===0?<ShieldCheck size={29}/>:i===1?<HeartPulse size={29}/>:<Activity size={29}/>}</span></div><p className="text-xs font-bold tracking-[.13em] text-[#0F766E]">{a[0]}</p><h3 className="mt-3 text-xl font-bold leading-7 text-[#163A5F]">{a[1]}</h3><div className="mt-5 flex items-center justify-between text-sm text-slate-500"><span>{a[2]}</span><ArrowRight size={18} className="transition group-hover:translate-x-1 group-hover:text-[#0F766E]"/></div></article>)}</div></div></section>

      <section id="contact" className="px-5 pb-24 sm:px-8 lg:pb-32"><div className="mx-auto grid max-w-[1344px] overflow-hidden rounded-[20px] bg-[#DFF6F0] lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 sm:p-12 lg:p-16"><p className="text-sm font-bold uppercase tracking-[.16em] text-[#0F766E]">Visit Clarity Health</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] text-[#163A5F]">Care is closer than you think.</h2><div className="mt-9 grid gap-6 sm:grid-cols-2"><div className="flex gap-3"><MapPin className="shrink-0 text-[#0F766E]"/><div><strong className="text-[#163A5F]">Main clinic</strong><p className="mt-2 text-sm leading-6 text-slate-600">240 Westfield Avenue<br/>Brookline, MA 02446</p></div></div><div className="flex gap-3"><Clock3 className="shrink-0 text-[#0F766E]"/><div><strong className="text-[#163A5F]">Opening hours</strong><p className="mt-2 text-sm leading-6 text-slate-600">Mon–Fri: 7am–7pm<br/>Sat: 8am–2pm</p></div></div></div><div className="mt-9 flex flex-wrap gap-3"><a href="https://maps.google.com" target="_blank" rel="noreferrer" className="rounded-2xl bg-[#163A5F] px-6 py-3.5 font-bold text-white">Get directions</a><a href="mailto:care@clarityhealth.com" className="rounded-2xl border border-[#163A5F]/15 bg-white px-6 py-3.5 font-bold text-[#163A5F]">Email us</a></div></div><div className="relative min-h-80 bg-[#DCEFFD]"><div className="absolute inset-0 opacity-30" style={{backgroundImage:'linear-gradient(#163A5F 1px,transparent 1px),linear-gradient(90deg,#163A5F 1px,transparent 1px)',backgroundSize:'48px 48px'}}/><div className="absolute left-[48%] top-[43%] grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white shadow-xl"><MapPin className="text-[#0F766E]" size={30}/></div><div className="absolute bottom-6 left-6 rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#163A5F] shadow-lg">Free covered parking</div></div></div></section>
    </main>

    <aside className="bg-[#0F766E] px-5 py-5 text-white sm:px-8" aria-label="Emergency information"><div className="mx-auto flex max-w-[1344px] flex-col items-center justify-between gap-4 sm:flex-row"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/15"><Phone/></span><div><strong>If this is a medical emergency</strong><p className="text-sm text-teal-50">Call emergency services immediately.</p></div></div><a href="tel:911" className="rounded-xl bg-white px-5 py-3 font-bold text-[#0F766E]">Call 911</a></div></aside>
    <footer className="bg-[#102F4D] px-5 pb-8 pt-16 text-blue-100 sm:px-8"><div className="mx-auto max-w-[1344px]"><div className="grid gap-12 border-b border-white/10 pb-12 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Logo light/><p className="mt-5 max-w-sm leading-7 text-blue-100/75">Exceptional medicine, thoughtfully delivered. Your health, your goals, and your life guide everything we do.</p><div className="mt-6 flex gap-3">{[Instagram,Linkedin,Facebook].map((Icon,i)=><a key={i} href="#top" aria-label="Social media" className="grid size-10 place-items-center rounded-xl bg-white/10 hover:bg-white/20"><Icon size={18}/></a>)}</div></div>{([['Care',['Primary Care','Specialties','Diagnostics','Virtual Care']],['Patients',['Book a Visit','Insurance','Patient Portal','FAQs']],['Company',['Our Story','Our Doctors','Careers','Contact']]] as [string,string[]][]).map(g=><div key={g[0]}><h3 className="font-bold text-white">{g[0]}</h3><ul className="mt-5 space-y-3">{g[1].map(x=><li key={x}><a href="#top" className="text-sm text-blue-100/70 hover:text-white">{x}</a></li>)}</ul></div>)}</div><div className="flex flex-col justify-between gap-3 pt-7 text-xs text-blue-100/55 sm:flex-row"><p>© 2026 Clarity Health. All rights reserved.</p><div className="flex gap-5"><a href="#top">Privacy</a><a href="#top">Accessibility</a><a href="#top">Terms</a></div></div></div></footer>
    {submitted && <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="fixed bottom-6 right-6 z-[70] flex max-w-sm items-start gap-3 rounded-2xl bg-white p-5 shadow-[0_20px_60px_rgba(22,58,95,.22)]"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#DFF6F0] text-[#0F766E]"><Check size={19}/></span><div><strong className="text-[#163A5F]">Request received</strong><p className="mt-1 text-sm text-slate-600">Our care team will call you shortly to confirm.</p></div><button onClick={()=>setSubmitted(false)} aria-label="Dismiss"><X size={18}/></button></motion.div>}
  </div>
}
