import { useEffect, useState } from 'react'
import { ArrowDown, ArrowRight, Check, Clock3, Leaf, Menu, Play, Sparkles, X } from 'lucide-react'

const treatments = [
  { number: '01', name: 'Kiyomi Renewal', meta: '90 min · $295', text: 'A slow, restorative ritual of warm stones, Japanese camellia oil and a reparative scalp massage.' },
  { number: '02', name: 'Mineral Immersion', meta: '120 min · $365', text: 'A full-body cocoon beginning with a mineral exfoliation and ending in a deeply nourishing wrap.' },
  { number: '03', name: 'Luminous Skin', meta: '75 min · $245', text: 'An illuminating facial pairing clinical botanicals with sculpting massage for a rested radiance.' },
]

function App() {
  const [open, setOpen] = useState(false)
  const [booked, setBooked] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [menu, setMenu] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 40); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenu(false) }

  return <main className="overflow-x-hidden bg-[#f8f5f1] text-[#3b3b3b]">
    <header className={`fixed inset-x-0 top-0 z-40 transition-all duration-500 ${scrolled ? 'border-b border-[#d8d1c7]/60 bg-[#fcfbf8]/85 shadow-sm backdrop-blur-xl' : 'bg-gradient-to-b from-black/30 to-transparent'}`}>
      <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10" aria-label="Primary navigation">
        <button onClick={() => scrollTo('top')} className={`font-serif text-2xl tracking-[.18em] ${scrolled ? 'text-[#3b3b3b]' : 'text-white'}`}>ÉLAN</button>
        <div className={`hidden items-center gap-8 text-xs font-medium uppercase tracking-[.16em] lg:flex ${scrolled ? 'text-[#3b3b3b]' : 'text-white/90'}`}>
          <button onClick={() => scrollTo('philosophy')}>Our approach</button><button onClick={() => scrollTo('treatments')}>Treatments</button><button onClick={() => scrollTo('rituals')}>Rituals</button><button onClick={() => scrollTo('therapists')}>The house</button>
        </div>
        <button onClick={() => setOpen(true)} className={`hidden rounded-full px-5 py-3 text-xs font-semibold uppercase tracking-[.15em] transition hover:-translate-y-0.5 lg:block ${scrolled ? 'bg-[#3b3b3b] text-white' : 'bg-white text-[#3b3b3b]'}`}>Reserve a ritual</button>
        <button onClick={() => setMenu(!menu)} className={`lg:hidden ${scrolled ? 'text-[#3b3b3b]' : 'text-white'}`} aria-label="Open navigation">{menu ? <X /> : <Menu />}</button>
      </nav>
      {menu && <div className="border-t border-[#d8d1c7] bg-[#fcfbf8] px-6 py-6 lg:hidden"><div className="flex flex-col gap-5 text-sm font-medium"><button onClick={() => scrollTo('philosophy')} className="text-left">Our approach</button><button onClick={() => scrollTo('treatments')} className="text-left">Treatments</button><button onClick={() => scrollTo('therapists')} className="text-left">The house</button><button onClick={() => { setOpen(true); setMenu(false) }} className="text-left text-[#8e7547]">Reserve a ritual</button></div></div>}
    </header>

    <section id="top" className="relative flex min-h-screen items-end overflow-hidden" aria-labelledby="hero-title">
      <img src="/images/hero-spa.jpg" alt="Sunlit treatment room with warm neutral furnishings" fetchPriority="high" className="absolute inset-0 h-full w-full object-cover" />
      <div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/16 to-black/10" />
      <div className="relative mx-auto w-full max-w-7xl px-6 pb-20 pt-40 lg:px-10 lg:pb-24">
        <p className="mb-5 flex items-center gap-3 text-xs uppercase tracking-[.25em] text-white/80"><span className="h-px w-8 bg-[#c9a96e]" /> Urban sanctuary · New York</p>
        <h1 id="hero-title" className="max-w-3xl font-serif text-5xl leading-[.98] text-white sm:text-6xl lg:text-8xl">A quieter kind<br /><em className="font-normal">of luxury.</em></h1>
        <div className="mt-8 flex max-w-xl flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><p className="max-w-sm text-base leading-7 text-white/80">A considered retreat for restoration, where ancient ritual meets exceptional modern care.</p><button onClick={() => setOpen(true)} className="group flex items-center gap-3 self-start rounded-full bg-[#fcfbf8] px-6 py-4 text-xs font-semibold uppercase tracking-[.15em] text-[#3b3b3b] shadow-xl transition hover:bg-[#c9a96e] hover:text-white">Book your treatment <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></button></div>
      </div>
      <button onClick={() => scrollTo('philosophy')} className="absolute bottom-8 right-6 flex items-center gap-3 text-[10px] uppercase tracking-[.2em] text-white/80 lg:right-10"><span className="hidden sm:block">Discover Élan</span><span className="flex h-10 w-10 animate-pulse items-center justify-center rounded-full border border-white/50"><ArrowDown size={14} /></span></button>
    </section>

    <section className="border-y border-[#d8d1c7]/70 bg-[#fcfbf8] py-5"><div className="mx-auto grid max-w-7xl grid-cols-1 gap-4 px-6 sm:grid-cols-3 lg:px-10"><Trust icon={<Check size={15} />} text="Certified therapists" /><Trust icon={<Leaf size={15} />} text="Conscious botanicals" /><Trust icon={<Sparkles size={15} />} text="A considered experience" /></div></section>

    <section id="philosophy" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-12 lg:items-center lg:px-10 lg:py-36">
      <div className="lg:col-span-5"><p className="eyebrow">The Élan philosophy</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Wellness, shaped <em className="font-normal">around you.</em></h2></div>
      <div className="lg:col-span-6 lg:col-start-7"><p className="text-lg leading-8 text-[#5a5956]">We believe in the profound value of unhurried time. Every encounter begins with a conversation, then unfolds as a bespoke expression of what your body and mind need most.</p><button onClick={() => scrollTo('treatments')} className="mt-8 inline-flex items-center gap-3 border-b border-[#a58955] pb-2 text-xs font-semibold uppercase tracking-[.16em] text-[#725d37]">Explore our treatments <ArrowRight size={15} /></button></div>
    </section>

    <section id="treatments" className="bg-[#e9e1d6]/55 py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="mb-12 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Signature treatments</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">A return to balance.</h2></div><button onClick={() => setOpen(true)} className="text-xs font-semibold uppercase tracking-[.15em] text-[#725d37]">View treatment menu <ArrowRight className="ml-2 inline" size={14} /></button></div><div className="grid gap-5 lg:grid-cols-3">{treatments.map((t) => <article key={t.name} className="group rounded-3xl border border-[#d8d1c7] bg-[#fcfbf8] p-7 shadow-[0_10px_30px_rgba(82,69,52,.06)] transition duration-500 hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(82,69,52,.12)]"><span className="text-xs tracking-[.2em] text-[#a58955]">{t.number}</span><h3 className="mt-12 font-serif text-3xl">{t.name}</h3><p className="mt-3 flex items-center gap-2 text-xs font-medium uppercase tracking-[.12em] text-[#8a8279]"><Clock3 size={13} /> {t.meta}</p><p className="mt-5 text-sm leading-6 text-[#68635d]">{t.text}</p><button onClick={() => setOpen(true)} className="mt-8 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[.14em] text-[#725d37]">Reserve <ArrowRight size={14} /></button></article>)}</div></div></section>

    <section id="rituals" className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-36"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative"><img loading="lazy" src="/images/treatment.jpg" alt="Therapist performing a calming massage treatment" className="h-[520px] w-full rounded-[2rem] object-cover" /><div className="absolute -bottom-6 -right-2 hidden w-48 rounded-2xl bg-[#a7b09e] p-6 text-[#fcfbf8] shadow-xl sm:block"><p className="font-serif text-3xl">92%</p><p className="mt-1 text-xs leading-5">of guests leave feeling deeply restored.</p></div></div><div className="lg:pl-16"><p className="eyebrow">The spa experience</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Let the world <em className="font-normal">fall away.</em></h2><p className="mt-6 max-w-lg leading-7 text-[#68635d]">Begin in our stone-warmed lounge with seasonal herbal tea. Your private suite becomes a sensory landscape—sound, scent and touch calibrated to ease you into stillness.</p><div className="mt-9 space-y-5">{['Private treatment suites', 'Thermal bathing & quiet lounge', 'Personalised post-treatment ritual'].map(x => <p key={x} className="flex items-center gap-4 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#e9e1d6] text-[#725d37]"><Check size={14}/></span>{x}</p>)}</div></div></div></section>

    <section id="therapists" className="bg-[#3b3b3b] py-24 text-[#fcfbf8] lg:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-2 lg:px-10"><div><p className="eyebrow text-[#c9a96e]">The hands behind the ritual</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Care, elevated<br /><em className="font-normal">to an art.</em></h2><p className="mt-6 max-w-md leading-7 text-white/65">Our therapists bring decades of international training and an instinctive, attentive approach to every moment of care.</p><button onClick={() => setOpen(true)} className="mt-8 inline-flex items-center gap-3 rounded-full border border-white/30 px-5 py-3 text-xs font-semibold uppercase tracking-[.14em] transition hover:bg-white hover:text-[#3b3b3b]">Meet our practitioners <ArrowRight size={14}/></button></div><div className="grid grid-cols-[1.1fr_.9fr] gap-5"><img loading="lazy" src="/images/therapist.jpg" alt="Élan wellness practitioner" className="h-96 w-full rounded-3xl object-cover" /><div className="flex flex-col justify-end rounded-3xl bg-[#595a52] p-6"><p className="font-serif text-2xl">“True luxury is feeling understood.”</p><p className="mt-5 text-xs uppercase tracking-[.15em] text-white/55">— Maya, Lead therapist</p></div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">From the apothecary</p><h2 className="mt-5 font-serif text-4xl leading-tight">The ritual continues <em className="font-normal">at home.</em></h2><p className="mt-6 max-w-sm leading-7 text-[#68635d]">Our edit of concentrated botanical formulas translates the Élan touch into a daily moment of care.</p><button onClick={() => setOpen(true)} className="mt-8 text-xs font-semibold uppercase tracking-[.15em] text-[#725d37]">Discover the collection <ArrowRight className="ml-2 inline" size={14}/></button></div><img loading="lazy" src="/images/skincare.jpg" alt="Essential oils for a home wellness ritual" className="h-80 w-full rounded-[2rem] object-cover lg:h-96" /></div></section>

    <section id="booking" className="bg-[#a7b09e] px-6 py-24 text-[#fcfbf8] lg:px-10 lg:py-32"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#f4e7cb]">Your time, held sacred</p><h2 className="mt-5 font-serif text-5xl leading-tight sm:text-6xl">Make space for<br /><em className="font-normal">yourself.</em></h2><p className="mx-auto mt-6 max-w-md leading-7 text-white/80">Reserve a moment of unhurried care, seven days a week.</p><button onClick={() => setOpen(true)} className="mt-9 rounded-full bg-[#fcfbf8] px-7 py-4 text-xs font-semibold uppercase tracking-[.15em] text-[#3b3b3b] shadow-lg transition hover:-translate-y-0.5 hover:bg-[#f4e7cb]">Begin your reservation</button></div></section>

    <footer className="bg-[#fcfbf8] px-6 py-12 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div><p className="font-serif text-2xl tracking-[.18em]">ÉLAN</p><p className="mt-4 max-w-xs text-sm leading-6 text-[#716c65]">A modern sanctuary for mind, body and skin.</p></div><div className="text-sm leading-7 text-[#716c65]"><p className="font-medium text-[#3b3b3b]">Visit</p><p className="mt-2">45 Mercer Street, New York<br />Daily · 9am – 8pm</p></div><div className="text-sm leading-7 text-[#716c65]"><p className="font-medium text-[#3b3b3b]">Stay in the know</p><p className="mt-2">Quiet notes on new rituals and seasonal care.</p></div></div><div className="mx-auto mt-12 flex max-w-7xl justify-between border-t border-[#d8d1c7] pt-5 text-[10px] uppercase tracking-[.14em] text-[#8a8279]"><span>© 2025 Élan House</span><span>Privacy · Terms</span></div></footer>

    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#3b3b3b]/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Reserve a ritual"><div className="relative w-full max-w-lg rounded-[2rem] bg-[#fcfbf8] p-7 shadow-2xl sm:p-10"><button onClick={() => { setOpen(false); setBooked(false) }} className="absolute right-6 top-6 text-[#69645d]" aria-label="Close reservation"><X size={20}/></button>{booked ? <div className="py-12 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#e3e8df] text-[#6b8062]"><Check/></div><h3 className="mt-5 font-serif text-3xl">We’ll be in touch.</h3><p className="mt-3 text-sm text-[#716c65]">Your request has been received with care.</p></div> : <form onSubmit={(e) => { e.preventDefault(); setBooked(true) }}><p className="eyebrow">Reservation request</p><h3 className="mt-4 font-serif text-3xl">Your ritual awaits.</h3><div className="mt-7 grid gap-4 sm:grid-cols-2"><input required aria-label="Your name" placeholder="Your name" className="rounded-xl border border-[#d8d1c7] bg-white px-4 py-3 text-sm outline-none focus:border-[#a58955]" /><input required type="email" aria-label="Email address" placeholder="Email address" className="rounded-xl border border-[#d8d1c7] bg-white px-4 py-3 text-sm outline-none focus:border-[#a58955]" /><select aria-label="Treatment" className="rounded-xl border border-[#d8d1c7] bg-white px-4 py-3 text-sm"><option>Choose a treatment</option><option>Kiyomi Renewal</option><option>Mineral Immersion</option><option>Luminous Skin</option></select><input type="date" aria-label="Preferred date" className="rounded-xl border border-[#d8d1c7] bg-white px-4 py-3 text-sm" /></div><button className="mt-6 w-full rounded-full bg-[#3b3b3b] py-4 text-xs font-semibold uppercase tracking-[.15em] text-white transition hover:bg-[#725d37]">Send request</button></form>}</div></div>}
  </main>
}

function Trust({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="flex items-center justify-center gap-3 text-xs font-medium uppercase tracking-[.14em] text-[#5c5a55]"><span className="text-[#a58955]">{icon}</span>{text}</div> }
export default App
